#!/bin/bash

function usage(){
    echo "stream - Illegal parameters"
    echo "Usage:"
    echo "   stream start"
    echo "   stream stop"
}

function streamStart(){
	videoPID=`pgrep -f video.py`
	if [ -n "$videoPID" ]; then
		echo "video is recording, use 'record stop' to stop."
		exit 1
	fi

	uv4lPID=`pgrep -f uv4l`
	if [ -n "$uv4lPID" ]; then
		echo "stream is already running, use 'stream stop' to stop."
		exit 1
	fi

	#h264
	uv4l --verbosity=-1 --driver raspicam --auto-video_nr --encoding h264 --width 640 --height 480 --enable-server on
	#uv4l --verbosity=-1 --driver raspicam --auto-video_nr --encoding h264 --width 1280 --height 720 --enable-server on
	
	ip=`ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`
	
	echo View the stream at:
	echo "   "http://$ip:8080/stream

}

function streamStop(){
	uv4lPID=`pgrep -f uv4l`
	if [ -n "$uv4lPID" ]; then
		echo "stopping video stream"
		sudo pkill uv4l
	else
		echo "video stream is not running, use 'stream start' to start."
		exit 1
	fi
}

if [ "$#" -ne 1 ]; then
    usage
    exit 1
fi


case "$1" in
	start) streamStart
		;;
	stop) streamStop
		;;
	*) usage
		;;
esac

exit 0

