#!/bin/bash

whitePin=8
irPin=7

function usage(){
    echo "light - Illegal parameters"
    echo "Usage:"
    echo "   light ir on"
    echo "   light ir off"
    echo "   light white on"
    echo "   light white off"
}

if [ "$#" -ne 2 ]; then
	usage
	exit 1
fi

videoPID=`pgrep -f video.py`
if [ -n "$videoPID" ]; then
	echo "video is recording, not allowed to control the lights"
	exit 1
fi

# idiomatic parameter and option handling in sh
while test $# -gt 0
do
    case "$1" in
        ir)
        	gpio -g mode $irPin out
        	case "$2" in
        		on) gpio -g write $irPin 1
					shift
					;;
				off) gpio -g write $irPin 0
					shift
					;;
				*) usage
					shift
					;;
			esac
        	;;
        white)
        	gpio -g mode $whitePin out
        	case "$2" in
        		on) gpio -g write $whitePin 1
					shift
					;;
				off) gpio -g write $whitePin 0
					shift
					;;
				*) usage
					shift
					;;
			esac
        	;;
        *) usage
            ;;
    esac
    shift
done

exit 0