#!/bin/bash

function usage(){
    echo "stream - Illegal parameters"
    echo "Usage:"
    echo "   stream start"
    echo "   stream stop"
}

function streamStart(){
	videoPID=`pgrep -f video.py`
	if [ -n "$videoPID" ]; then
		echo "video is recording, use 'record stop' to stop."
		exit 1
	fi

	# this will list process if it is zombie, e.g. <defunct>
	# ps -lA | grep '^. Z'
	uv4lPID=`pgrep -f uv4l`
	if [ -n "$uv4lPID" ]; then
		echo "stream is already running, use 'stream stop' to stop."
		#exit 1
	fi

	#h264
	#sudo service uv4l_raspicam start
	# this will start uv4l process as root, to kill be sure to use 'sudo'
	uv4l --verbosity=-1 --driver raspicam --auto-video_nr --encoding h264 --width 640 --height 480 --enable-server on
	
	ip=`ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`
	
	echo View the stream at:
	echo "   "http://$ip:8080/stream

}

function streamStop(){
	uv4lPID=`pgrep -f uv4l`
	if [ -n "$uv4lPID" ]; then
		# we never get here
		echo "stopping video stream ..."
		sudo kill -- -$uv4lPID
		#sudo service uv4l_raspicam stop
		#sudo pkill uv4l
		#sudo kill -9 $uv4lPID
		echo "done"
	else
		echo "video stream is not running, use 'stream start' to start."
		exit 1
	fi
}

if [ "$#" -ne 1 ]; then
    usage
    exit 1
fi


case "$1" in
	start) streamStart
		;;
	stop) streamStop
		;;
	*) usage
		;;
esac

exit 0

