#!/bin/bash

#echo Killing all python processes
#killall python


videoPID=`pgrep -f video.py`
if [ -n "$videoPID" ]; then
    echo stopping video
    kill $videoPID > /dev/null
else
    echo video is not running
fi


lightsPID=`pgrep -f lights.py`
if [ -n "$lightsPID" ]; then
    echo stopping lights
    kill $lightsPID > /dev/null
else
    echo lights is not running
fi