#!/bin/bash

videoPID=`pgrep -f video.py`
if [ -n "$videoPID" ]; then
    echo video is already running
    #echo killing video
    #kill $videoPID > /dev/null
else
	echo Running video
	python /home/pi/Sites/homecage/video.py &
fi

lightsPID=`pgrep -f lights.py`
if [ -n "$lightsPID" ]; then
    echo lights is already running
    #echo killing lights
    #kill $lightsPID > /dev/null
else
	echo Running lights
	python /home/pi/Sites/homecage/lights.py &
fi


